modified hello

diff --git a/.github/workflows/hello.yml b/.github/workflows/hello.yml
--- a/.github/workflows/hello.yml
+++ b/.github/workflows/hello.yml
@@ -36,5 +36,5 @@ jobs:
       - name: Print OS name 
         run: echo "$RUNNER_OS"
 
-        - name: Intentional Failure Step
-         run: exit 1
+      #  - name: Intentional Failure Step
+      #   run: exit 1
